version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "leaderboard-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qjzo1zlctrax"
s3_prefix = "leaderboard-bot"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
container_env_vars_file = ".env.json"