version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "leaderboard-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qjzo1zlctrax"
s3_prefix = "leaderboard-bot"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "ClientSecret=\"DPyicB72FT3eWHt-_RKJaLyT794mkNKS\" DiscordToken=\"MTA4MDMzNTQyNDkwNTU0Nzg2Nw.GNip_Q.WWG0k8U59N2MEQnmYplWr12_lon8N8zRPpAOL0\""
