AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A discord leaderboard/submission bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Parameters:
  ClientSecret:
    Type: String
    Default: unset
  DiscordToken:
    Type: String
    Default: unset

Resources:
  InvocationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: invocation.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Environment:
        Variables:
          CLIENT_ID: '1080335424905547867'
          PUBLIC_KEY: 019df6dfc4e2f506284fb0e4c5474808d3e9cc16c2e3a6491359eb85d49f82c6
          DB_TABLE_NAME: !Ref LeaderboardTable
          CLIENT_SECRET: !Ref ClientSecret
          DISCORD_TOKEN: !Ref DiscordToken
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeaderboardTable
      Events:
        Invocation:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /invocations
            Method: post
      Tracing: Active
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: false
        EntryPoints:
          - src/invocation.ts
  LeaderboardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
      - AttributeName: LeaderboardId
        AttributeType: N
      - AttributeName: Timestamp
        AttributeType: N
      - AttributeName: GuildAndChannelId
        AttributeType: S
      KeySchema:
      - AttributeName: LeaderboardId
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: "guildAndChannel"
        KeySchema:
          - AttributeName: GuildAndChannelId
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InvocationApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invocations/'
  InvocationFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt InvocationFunction.Arn
  InvocationFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt InvocationFunctionRole.Arn
